### ISSUE TITLE
Petergate doesnt work with MongoID

### ISSUE THREAD

**Issue by joelGarcia93** [elorest/petergate#28]
hello everyone im trying to use petergate with mongo Db but Im getting this exception.

> There was an error while trying to load the gem 'petergate'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveRecord

someone can help me? Thank you so much

**Comment by elorest** [comment]
Petergate works by overloading activerecord base, which is default in Rails. Much of the code would work fine with another ORM, but since it's not very common and the community doesn't even use the same mongodb wrapper within rails, it's not worth supporting by default. It's possible that there's a gem that would allow you to use mongo with activerecord.
