### ISSUE TITLE
Setting role that are not available on available_roles clears all the roles except :user role?

### ISSUE THREAD

**Issue by codemilan** [elorest/petergate#38]
I don't know is this issue or intended behaviour. When I try to set roles that are not available on available_roles then roles are reset to :users only, clearing all other roles set previously.
```ruby
u = User.first
u.available_roles # gives [:root_admin, :admin, :manager]
u.roles # gives [:admin, :user]
u.update(roles: :test) #sets role to :user only clearing all other previously set roles.
u.roles # gives [:user]
```

Is this behaviour intended or is an issue. 
Needed insight if I want to add error message on user object if invalid role is tried to set, without clearing previously set roles.

**Comment by Uzval-Mallepeddi** [comment]
@codemilan Since you don't the role "test" set in the Users model, if you are trying to set an unknown role to the user, petergate reverts you back to :user role which is intended behaviour of petergate gem.

If you want to set a default role for user on signup, you can do it by specifying it as a default option in schema by migration.

**Comment by elorest** [comment]
@codemilan I've you're using `multiple: false` then it would be really easy to add a validation to your user model. 

`validates :roles, inclusion: { in: self.available_roles), message: "%{value} is not a valid role!" }`

This isn't included by default because there are many ways that roles could be set or unset so I didn't want to force people into one way of doing it.

**Comment by codemilan** [comment]
Thank you @elorest and @Uzval-Mallepeddi your responses totally makes sense.
